.TH "LOUNGER\-ISONLINE" "1" "January 2016" "" ""
.SH "NAME"
\fBlounger-isonline\fR \- check if a database is online
.P
.RS 2
.nf
lounger isonline <url> [\-\-json]
.fi
.RE
.SH DESCRIPTION
.P
Check if a database is online and available\.
.P
url:
The url must be an url that is using the http or https protocol\.
.P
\fBisonline\fP prints the result as human readable output\. JSON output is
also supported by passing the \fB\-\-json\fP flag\.

